name = "gridify-expiry-automation"
main = "functions/expiry-automation.js"
compatibility_date = "2024-04-01"

[triggers]
crons = ["*/30 * * * *"] # Runs every 30 minutes to check if it matches the user's preferred time
